AWSTemplateFormatVersion: "2010-09-09"
Description: ChatGPT API Usage Tracking System

Parameters:
  TableName:
    Type: String
    Default: chatgpt_usage_tracking
    Description: Name of the DynamoDB table for storing usage data
  DeploymentBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package
  DeploymentPackageKey:
    Type: String
    Description: S3 key for Lambda deployment package

Resources:
  # DynamoDB Table for Usage Tracking
  ChatGPTUsageTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: organization_id
          KeyType: HASH
        - AttributeName: user_id#timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: OrgTimestampIndex
          KeySchema:
            - AttributeName: organization_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserTimestampIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Lambda Function Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ChatGPTUsageTable.Arn

  # Lambda Function
  ChatGPTUsageFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentPackageKey
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TableName
          POWERTOOLS_SERVICE_NAME: chatgpt-usage-tracker
          LOG_LEVEL: INFO

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: ChatGPT Usage Tracking API
      Description: API for tracking ChatGPT usage

  ApiResource:
    Type: AWS::ApiGateway::Resource
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: track

  ApiMethod:
    Type: AWS::ApiGateway::Method
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ChatGPTUsageFunction.Arn}/invocations

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway

  ApiStage:
    Type: AWS::ApiGateway::Stage
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: Prod

  # Lambda Permission for API Gateway
  LambdaPermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ChatGPTUsageFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/POST/track

  # Lambda Function for Getting Costs
  GetCostsFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentPackageKey
      Handler: get_costs_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TableName
          POWERTOOLS_SERVICE_NAME: chatgpt-usage-tracker
          LOG_LEVEL: INFO

  # API Gateway Resource for Get Costs
  GetCostsResource:
    Type: AWS::ApiGateway::Resource
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: costs

  GetCostsMethod:
    Type: AWS::ApiGateway::Method
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref GetCostsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCostsFunction.Arn}/invocations
      RequestParameters:
        method.request.querystring.user_id: false
        method.request.querystring.organization_id: false
        method.request.querystring.start_date: false
        method.request.querystring.end_date: false

  # Lambda Permission for Get Costs API Gateway
  GetCostsLambdaPermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetCostsFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/GET/costs

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for the ChatGPT usage tracking function
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/track"

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref TableName

  LambdaFunction:
    Description: Lambda function name
    Value: !Ref ChatGPTUsageFunction

  GetCostsApiEndpoint:
    Description: API Gateway endpoint URL for getting costs
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/costs"
