name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
      - get_all_costomers
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  STACK_NAME: chatgpt-usage-tracker
  LAMBDA_ZIP: lambda-package.zip
  GET_COSTS_ZIP: get-costs-package.zip
  GET_ORG_COSTS_ZIP: get-org-costs-package.zip
  REGISTER_ORG_ZIP: register-org-package.zip

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awscli boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Package and Upload Lambda
        run: |
          # Create temporary directories for packaging
          mkdir -p package/track
          mkdir -p package/costs
          mkdir -p package/org-costs
          mkdir -p package/register-org

          # Copy Lambda functions to their respective directories
          cp lambda_function.py package/track/
          cp get_costs_function.py package/costs/
          cp get_org_costs_function.py package/org-costs/
          cp register_org_function.py package/register-org/

          # Install dependencies for all functions
          cd package/track
          pip install \
            boto3==1.28.38 \
            python-json-logger==2.0.7 \
            -t .

          cd ../costs
          pip install \
            boto3==1.28.38 \
            python-json-logger==2.0.7 \
            -t .

          cd ../org-costs
          pip install \
            boto3==1.28.38 \
            python-json-logger==2.0.7 \
            -t .

          cd ../register-org
          pip install \
            boto3==1.28.38 \
            python-json-logger==2.0.7 \
            -t .
          cd ../..

          # Remove unnecessary files from all packages
          find package -type d -name "__pycache__" -exec rm -rf {} +
          find package -type d -name "*.dist-info" -exec rm -rf {} +
          find package -type d -name "*.egg-info" -exec rm -rf {} +

          # Create deployment packages
          cd package/track
          zip -r ../../${{ env.LAMBDA_ZIP }} ./*
          cd ../costs
          zip -r ../../${{ env.GET_COSTS_ZIP }} ./*
          cd ../org-costs
          zip -r ../../${{ env.GET_ORG_COSTS_ZIP }} ./*
          cd ../register-org
          zip -r ../../${{ env.REGISTER_ORG_ZIP }} ./*
          cd ../..

          # Show contents for debugging
          echo "Contents of track package:"
          unzip -l ${{ env.LAMBDA_ZIP }}
          echo "Contents of costs package:"
          unzip -l ${{ env.GET_COSTS_ZIP }}
          echo "Contents of org-costs package:"
          unzip -l ${{ env.GET_ORG_COSTS_ZIP }}
          echo "Contents of register-org package:"
          unzip -l ${{ env.REGISTER_ORG_ZIP }}

          # Set S3 keys with timestamp
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          S3_KEY="deployments/$TIMESTAMP/${{ env.LAMBDA_ZIP }}"
          COSTS_S3_KEY="deployments/$TIMESTAMP/${{ env.GET_COSTS_ZIP }}"
          ORG_COSTS_S3_KEY="deployments/$TIMESTAMP/${{ env.GET_ORG_COSTS_ZIP }}"
          REGISTER_ORG_S3_KEY="deployments/$TIMESTAMP/${{ env.REGISTER_ORG_ZIP }}"
          echo "LAMBDA_S3_KEY=$S3_KEY" >> $GITHUB_ENV
          echo "GET_COSTS_S3_KEY=$COSTS_S3_KEY" >> $GITHUB_ENV
          echo "GET_ORG_COSTS_S3_KEY=$ORG_COSTS_S3_KEY" >> $GITHUB_ENV
          echo "REGISTER_ORG_S3_KEY=$REGISTER_ORG_S3_KEY" >> $GITHUB_ENV

          # Upload to S3
          aws s3 cp ${{ env.LAMBDA_ZIP }} s3://${{ secrets.AWS_S3_BUCKET }}/$S3_KEY
          aws s3 cp ${{ env.GET_COSTS_ZIP }} s3://${{ secrets.AWS_S3_BUCKET }}/$COSTS_S3_KEY
          aws s3 cp ${{ env.GET_ORG_COSTS_ZIP }} s3://${{ secrets.AWS_S3_BUCKET }}/$ORG_COSTS_S3_KEY
          aws s3 cp ${{ env.REGISTER_ORG_ZIP }} s3://${{ secrets.AWS_S3_BUCKET }}/$REGISTER_ORG_S3_KEY

          # Verify uploads
          aws s3api head-object --bucket ${{ secrets.AWS_S3_BUCKET }} --key $S3_KEY || {
            echo "Failed to verify track function upload"
            exit 1
          }
          aws s3api head-object --bucket ${{ secrets.AWS_S3_BUCKET }} --key $COSTS_S3_KEY || {
            echo "Failed to verify get costs function upload"
            exit 1
          }
          aws s3api head-object --bucket ${{ secrets.AWS_S3_BUCKET }} --key $ORG_COSTS_S3_KEY || {
            echo "Failed to verify get org costs function upload"
            exit 1
          }
          aws s3api head-object --bucket ${{ secrets.AWS_S3_BUCKET }} --key $REGISTER_ORG_S3_KEY || {
            echo "Failed to verify register org function upload"
            exit 1
          }
          echo "S3 uploads verified successfully"

      - name: Check and Delete Failed Stack
        run: |
          # Check if stack exists and is in ROLLBACK_COMPLETE state
          STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "STACK_NOT_FOUND")

          if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
            echo "Stack is in ROLLBACK_COMPLETE state. Deleting stack..."
            aws cloudformation delete-stack --stack-name ${{ env.STACK_NAME }}
            echo "Waiting for stack deletion to complete..."
            aws cloudformation wait stack-delete-complete --stack-name ${{ env.STACK_NAME }}
            echo "Stack deleted successfully"
          fi

      - name: Deploy CloudFormation Stack
        run: |
          echo "Deploying with parameters:"
          echo "DeploymentBucket: ${{ secrets.AWS_S3_BUCKET }}"
          echo "DeploymentPackageKey: ${{ env.LAMBDA_S3_KEY }}"
          echo "GetCostsPackageKey: ${{ env.GET_COSTS_S3_KEY }}"
          echo "GetOrgCostsPackageKey: ${{ env.GET_ORG_COSTS_S3_KEY }}"
          echo "RegisterOrgPackageKey: ${{ env.REGISTER_ORG_S3_KEY }}"

          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DeploymentBucket=${{ secrets.AWS_S3_BUCKET }} \
              DeploymentPackageKey=${{ env.LAMBDA_S3_KEY }} \
              GetCostsPackageKey=${{ env.GET_COSTS_S3_KEY }} \
              GetOrgCostsPackageKey=${{ env.GET_ORG_COSTS_S3_KEY }} \
              RegisterOrgPackageKey=${{ env.REGISTER_ORG_S3_KEY }}
